# Generated by Django 2.2 on 2019-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190413_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('course', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
