# Generated by Django 2.2 on 2019-04-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_review_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='num_ratings',
        ),
    ]
