# Generated by Django 2.2 on 2019-04-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
