# Generated by Django 2.2 on 2019-04-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
