# Generated by Django 2.2 on 2019-04-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='follower',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='userId',
            new_name='user',
        ),
    ]
