# Generated by Django 2.2 on 2019-04-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190414_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileImage',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='static/images/myprofile.jpg', upload_to=''),
        ),
    ]
