# Generated by Django 2.2 on 2019-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190415_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='/accounts/templates/static/images/myprofile.jpg', upload_to=''),
        ),
    ]
