# Generated by Django 2.2 on 2019-04-17 03:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190416_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/myprofile.jpg', upload_to=accounts.models.user_profile_path),
        ),
    ]
