# Generated by Django 2.2 on 2019-04-20 06:00

from django.db import migrations
import social_django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190417_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=social_django.fields.JSONField(default=dict),
        ),
    ]
