# Generated by Django 2.2 on 2019-04-19 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190417_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='followed',
        ),
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
