# Generated by Django 2.2 on 2019-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190419_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
