# Generated by Django 2.2 on 2019-04-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190419_1317'),
        ('accounts', '0009_auto_20190420_1600'),
    ]

    operations = [
    ]
