# Generated by Django 2.2 on 2019-04-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190413_1808'),
        ('accounts', '0012_merge_20190420_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentCourses',
            field=models.ManyToManyField(related_name='currentCourses', to='courses.Courses'),
        ),
        migrations.CreateModel(
            name='Tutorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='previousCourses',
            field=models.ManyToManyField(related_name='previousCourses', through='accounts.Tutorship', to='courses.Courses'),
        ),
    ]
