# Generated by Django 2.2 on 2019-04-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190422_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
