# Generated by Django 2.2 on 2019-04-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190423_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
        migrations.AlterField(
            model_name='tutorship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='accounts.Profile'),
        ),
    ]
